### PR TITLE
Updated 'Alaindia' spawn pos, movetype and added waypoints.

### PR DESCRIPTION
**Pull request by cressidagp**
db: b2faeda90a89783b05f5e5cffdf9b9a941cff710

.npc portto 28716

### CODE REVIEW

**Comment by dfighter1985** [comment]
She seems to disappear after a while. I don't know if it's a waypoint issue or Arcemu issue, or she just is afraid of me.
Can you investigate please?

**Comment by cressidagp** [comment]
I Will do it good men

**Comment by cressidagp** [comment]
> .npc portto 28716

All right, i reduced the wait delay to make a quick test and did the full circle following Alaindia from back.

Probably she walked into an inactive map cell.  As far as i know, there isnt a creature override (or any other stuff) to force them to activate map cells

**Comment by dfighter1985** [comment]
> > She seems to disappear after a while. I don't know if it's a waypoint issue or Arcemu issue, or she just is afraid of me. Can you investigate please?
> 
> All right, i reduced the wait delay to make a quick test and did the full circle following Alaindia from back. Worked fine.
> 
> Probably she walked into an inactive map cell. As far as i know, there isnt a creature override (or any other stuff) to force them to activate map cells

I think I've solved the mystery!
It's not inactive map cells. It's that the npc portto command works differently than what I expected.
It ports you to the spawn point of the NPC, not to the NPC...
/facepalm

**Comment by dfighter1985** [comment]
Merged. Thanks!

**Pull request merged**
