### PR TITLE
Added 'Meven Korgal' monstersay

### PR DESCRIPTION
**Pull request by cressidagp**
db: b2faeda90a89783b05f5e5cffdf9b9a941cff710

On enter combat he will chat (not yell)  one of the following texts:

'The Scarlet Crusade shall not fail in its mission!'
'These lands shall be cleansed!'

.npc portto 12221

### CODE REVIEW

**Comment by dfighter1985** [comment]
The database already has 3 monster say texts for this npc.

```
entry	event	chance	language	type	monstername	text0	text1	text2	text3	text4
1667	0	50	0	12	Meven Korgal	These lands shall be cleansed!	These undead atrocities will be destroyed!	The Scarlet Crusade shall not fail in its mission!	\N	\N
```

However both the database and your patch are missing one.
See here:
https://wowwiki-archive.fandom.com/wiki/Meven_Korgal#Quotes

**Comment by cressidagp** [comment]
Hi there! The ones i added are for OnEnterCombat.

The texts on db are for random chat when si out of combat.

 Sadly, there isnt a monstersay event for that.

**Comment by dfighter1985** [comment]
> Hi there! The ones i added are for OnEnterCombat.
> 
> The texts on db are for random chat when its out of combat.
> 

Ok, I see. Merged it.

> Sadly, there isnt a monstersay event for that.

Not yet. But I guess I know a guy who can make events like that :)

**Comment by cressidagp** [comment]
> > Hi there! The ones i added are for OnEnterCombat.
> > The texts on db are for random chat when its out of combat.
> 
> Ok, I see. Merged it. Thanks!
> 
> > Sadly, there isnt a monstersay event for that.
> 
> Not yet. But I guess I know a guy who can make events like that :)

Oh yeah, i forget about that APE dude :D

**Pull request merged**
